### ISSUE TITLE
ImportError: The descartes package is required for plotting polygons in geopandas.

### ISSUE THREAD

**Issue by rgdonohue** [christyheaton/PlanYourNextEclipseViewing#1]
Hi. Really like your notebook and presentation/project!

Apologies for posting this as an Issue as it's likely not an issue on your end. I feel like this keeps happening to me with Python dev and I can't quite figure out why.

After installing everything with your environment.yml file and launching the notebook I get an import error. It says that descartes is required for geopandas (which I'm not sure it is ...). So I install it. `conda list` shows it's in the geopandasenv environment. I even restart the kernel and even kill the notebook and relaunch the notebook, but I still get the same error:

![image](https://user-images.githubusercontent.com/1952205/63983838-819d8500-ca96-11e9-81f6-0964789ca3ea.png)

MacOS 10.14.6. Updated conda environment. ¯\_(ツ)_/¯ ... I :heart: Node JS hahaha.

**Comment by christyheaton** [comment]
It looks like descartes was removed from geopandas dependencies after I created the environment.yml. I have added it, so if you use the latest files it should work (it just did for me). I only have access to Windows 10 for testing though. I hope it works for you!
